services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    # Use variable interpolation from a .env file for the port and other secrets
    environment:
      -  PORT=3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - myPortfolio-network
    restart: unless-stopped # Added restart policy

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      # Changed from 'localhost' to the service name 'nginx' for inter-container comms
      VITE_API_URL: http://nginx/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - myPortfolio-network
    restart: unless-stopped # Added restart policy

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - myPortfolio-network
    restart: unless-stopped # Added restart policy

networks:
  myPortfolio-network:
    driver: bridge

volumes:
  jenkins_home:
