services:
  backend:
    build: ./backend
    ports:
      - "5001"  # container port exposed; host port will be dynamically assigned if needed
    environment:
      - PORT=5001
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - myportfolio-network

  frontend:
    build: ./frontend
    ports:
      - "5173"
    environment:
      - VITE_API_URL=http://localhost/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - myportfolio-network

  nginx:
    build: ./nginx
    ports:
      - "80"
    depends_on:
      - frontend
      - backend
    networks:
      - myportfolio-network

  jenkins:
    build: ./jenkins
    user: root
    ports:
      - "8080"
      - "50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - myportfolio-network

networks:
  myportfolio-network:
    driver: bridge

volumes:
  jenkins_home:
